-- PersonalColor App — initial schema (Phase 3)
-- Project rules (CLAUDE.md):
--   * soft delete only (deleted_at on every table) — nothing is ever hard-deleted
--   * RLS uses auth.jwt()->>'sub' (Clerk third-party auth), NOT auth.uid()
--   * SECURITY DEFINER functions always pin search_path (public, pg_temp)
--
-- Write model: diagnoses / drape_responses / photos are written ONLY by the
-- server (service role). A completed diagnosis is persisted atomically and
-- idempotently via persist_completed_diagnosis() — clients never insert
-- results directly (tamper-proofing for the Phase 5 paid-diagnosis model).
-- Clients read their own rows; guests claim rows after login via
-- claim_diagnosis().
--
-- NOTE (pre-Phase 5 TODOs):
--   * The bare diagnosis UUID acts as the guest-claim capability for the MVP.
--     Before monetization, replace with a hashed one-time claim token with an
--     expiry, checked server-side against entitlements — and at that point
--     revoke authenticated execute on claim_diagnosis (service_role only).
--   * Account policy (decided): re-signup reactivates a tombstoned users row.
--     Clerk is the source of truth for accounts — the upsert paths below only
--     run for Clerk-authenticated users, so a lingering tombstone is stale by
--     definition. Permanent deletion, if ever needed, is enforced by deleting
--     the user in Clerk (this code path then becomes unreachable).

begin;

-- Postgres 15+ already denies CREATE on public to PUBLIC; keep it explicit.
revoke create on schema public from public;

create type season_type as enum ('spring_warm', 'summer_cool', 'autumn_warm', 'winter_cool');

-- ---------------------------------------------------------------------------
-- users — Clerk is the source of truth; this table only references it.
-- No client insert policy: rows are upserted by the SECURITY DEFINER
-- functions below (claim) and by the server persist RPC.
-- ---------------------------------------------------------------------------
create table users (
  id text primary key, -- Clerk sub
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table users enable row level security;

create policy "users select own" on users
  for select to authenticated
  using (id = (select auth.jwt()->>'sub') and deleted_at is null);

-- ---------------------------------------------------------------------------
-- diagnoses — one row per COMPLETED hybrid diagnosis, written once via
-- persist_completed_diagnosis(). Final fields are intentionally NOT NULL:
-- partial diagnoses are never persisted. user_id nullable = guest usage.
-- ---------------------------------------------------------------------------
create table diagnoses (
  id uuid primary key, -- pre-generated by the server; doubles as idempotency key
  user_id text references users (id),
  llm_initial_season_type season_type not null,
  llm_runner_up_season_type season_type not null,
  llm_confidence numeric(3, 2) not null check (llm_confidence between 0 and 1),
  is_borderline boolean not null default false,
  final_season_type season_type not null,
  subtype text not null,
  final_confidence numeric(3, 2) not null check (final_confidence between 0 and 1),
  combination_method text not null
    check (combination_method in ('llm_confirmed', 'draping_shifted', 'llm_default')),
  color_metadata jsonb not null check (jsonb_typeof(color_metadata) = 'object'),
  card_image_url text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  check (llm_runner_up_season_type <> llm_initial_season_type),
  check (
    (final_season_type = 'spring_warm' and subtype in ('bright', 'light'))
    or (final_season_type = 'summer_cool' and subtype in ('light', 'mute'))
    or (final_season_type = 'autumn_warm' and subtype in ('mute', 'deep'))
    or (final_season_type = 'winter_cool' and subtype in ('bright', 'deep'))
  ),
  -- Mirrors combine() semantics: draping only ever shifts to the runner-up.
  -- Server recomputation is the primary defense; this is the last line.
  check (
    (combination_method = 'draping_shifted' and final_season_type = llm_runner_up_season_type)
    or (combination_method in ('llm_confirmed', 'llm_default')
        and final_season_type = llm_initial_season_type)
  )
);

create index diagnoses_user_idx on diagnoses (user_id, created_at desc) where deleted_at is null;

alter table diagnoses enable row level security;

create policy "diagnoses select own" on diagnoses
  for select to authenticated
  using (user_id = (select auth.jwt()->>'sub') and deleted_at is null);

-- ---------------------------------------------------------------------------
-- drape_responses — one row per draping round, persisted in the same
-- transaction as the parent diagnosis. Option seasons are recorded so results
-- stay reproducible even if the palette changes later.
-- ---------------------------------------------------------------------------
create table drape_responses (
  id uuid primary key default gen_random_uuid(),
  diagnosis_id uuid not null references diagnoses (id),
  round_number int not null check (round_number between 1 and 3),
  axis text not null check (axis in ('temperature', 'depth', 'chroma')),
  color_option_a text not null check (color_option_a ~ '^#[0-9A-Fa-f]{6}$'),
  color_option_b text not null check (color_option_b ~ '^#[0-9A-Fa-f]{6}$'),
  option_a_season_type season_type not null,
  option_b_season_type season_type not null,
  user_choice text not null check (user_choice in ('a', 'b')),
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  check (color_option_a <> color_option_b),
  check (option_a_season_type <> option_b_season_type),
  unique (diagnosis_id, round_number) -- also serves as the diagnosis_id lookup index
);

alter table drape_responses enable row level security;

create policy "drape_responses select own" on drape_responses
  for select to authenticated
  using (
    deleted_at is null
    and exists (
      select 1 from diagnoses d
      where d.id = diagnosis_id
        and d.user_id = (select auth.jwt()->>'sub')
        and d.deleted_at is null
    )
  );

-- ---------------------------------------------------------------------------
-- photos — temporary R2 references, service-role only (no client policies).
-- diagnosis_id nullable: the photo is uploaded BEFORE a diagnosis exists.
-- The R2 object is physically deleted right after analysis (bucket lifecycle
-- rule as backstop); the row is only ever tombstoned.
-- ---------------------------------------------------------------------------
create table photos (
  id uuid primary key default gen_random_uuid(),
  diagnosis_id uuid references diagnoses (id),
  r2_key text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  deleted_at timestamptz -- set when the R2 object is confirmed deleted
);

create index photos_expires_idx on photos (expires_at) where deleted_at is null;

alter table photos enable row level security; -- no policies: service role only

-- ---------------------------------------------------------------------------
-- designers — founder-curated directory. Publicly readable, server-managed.
-- ---------------------------------------------------------------------------
create table designers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  salon_name text not null,
  specialties season_type[] not null default '{}',
  region text not null,
  contact_info jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index designers_region_idx on designers (region) where deleted_at is null;
create index designers_specialties_idx on designers using gin (specialties)
  where deleted_at is null;

alter table designers enable row level security;

create policy "designers public read" on designers
  for select to anon, authenticated
  using (deleted_at is null);

-- ---------------------------------------------------------------------------
-- persist_completed_diagnosis — atomic, idempotent persistence of a finished
-- diagnosis + its draping rounds. Service-role only: the server recomputes
-- the final result before calling this (clients are never trusted with it).
-- Re-submitting the same diagnosis id is a no-op returning the id.
-- ---------------------------------------------------------------------------
create or replace function public.persist_completed_diagnosis(
  p_diagnosis_id uuid,
  p_user_id text,
  p_llm_initial season_type,
  p_llm_runner_up season_type,
  p_llm_confidence numeric,
  p_is_borderline boolean,
  p_final_season season_type,
  p_subtype text,
  p_final_confidence numeric,
  p_combination_method text,
  p_color_metadata jsonb,
  p_card_image_url text,
  p_rounds jsonb -- [{round_number, axis, color_option_a, color_option_b,
                 --   option_a_season_type, option_b_season_type, user_choice}]
)
returns uuid
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row record;
  v_count int;
  v_round_no int;
  v_option_a season_type;
  v_option_b season_type;
  v_inserted_id uuid;
begin
  -- Validate the rounds payload shape before touching any table.
  if p_rounds is null or jsonb_typeof(p_rounds) <> 'array' then
    raise exception 'p_rounds must be a JSON array';
  end if;
  v_count := jsonb_array_length(p_rounds);
  if v_count < 2 or v_count > 3 then
    raise exception 'expected 2-3 draping rounds, got %', v_count;
  end if;

  if p_user_id is not null then
    -- Reactivate tombstoned accounts on re-signup.
    insert into public.users (id) values (p_user_id)
    on conflict (id) do update set deleted_at = null;
  end if;

  -- Concurrency-safe idempotency: the server pre-generates the id, so a retry
  -- (or a concurrent duplicate) resolves atomically at the PK, not via a
  -- check-then-insert race. Only the call that actually inserted the row
  -- writes the rounds.
  insert into public.diagnoses (
    id, user_id, llm_initial_season_type, llm_runner_up_season_type,
    llm_confidence, is_borderline, final_season_type, subtype,
    final_confidence, combination_method, color_metadata, card_image_url
  ) values (
    p_diagnosis_id, p_user_id, p_llm_initial, p_llm_runner_up,
    p_llm_confidence, p_is_borderline, p_final_season, p_subtype,
    p_final_confidence, p_combination_method, p_color_metadata, p_card_image_url
  )
  on conflict (id) do nothing
  returning id into v_inserted_id;

  if v_inserted_id is null then
    return p_diagnosis_id; -- already persisted by an earlier/concurrent call
  end if;

  for v_row in
    select value, ordinality from jsonb_array_elements(p_rounds) with ordinality
  loop
    if jsonb_typeof(v_row.value) <> 'object' then
      raise exception 'round % must be a JSON object', v_row.ordinality;
    end if;
    v_round_no := (v_row.value->>'round_number')::int;
    if v_round_no is null or v_round_no < 1 or v_round_no > v_count then
      raise exception 'round_number must be between 1 and %', v_count;
    end if;
    v_option_a := (v_row.value->>'option_a_season_type')::season_type;
    v_option_b := (v_row.value->>'option_b_season_type')::season_type;
    -- Every round must drape exactly the two candidate seasons.
    if not (
      (v_option_a = p_llm_initial and v_option_b = p_llm_runner_up)
      or (v_option_a = p_llm_runner_up and v_option_b = p_llm_initial)
    ) then
      raise exception 'round % options must be the two candidate seasons', v_round_no;
    end if;

    insert into public.drape_responses (
      diagnosis_id, round_number, axis, color_option_a, color_option_b,
      option_a_season_type, option_b_season_type, user_choice
    ) values (
      p_diagnosis_id,
      v_round_no,
      v_row.value->>'axis',
      v_row.value->>'color_option_a',
      v_row.value->>'color_option_b',
      v_option_a,
      v_option_b,
      v_row.value->>'user_choice'
    );
    -- duplicate round numbers hit unique(diagnosis_id, round_number) and roll
    -- the whole transaction back, diagnosis row included.
  end loop;

  return p_diagnosis_id;
end;
$$;

revoke execute on function public.persist_completed_diagnosis(
  uuid, text, season_type, season_type, numeric, boolean, season_type, text,
  numeric, text, jsonb, text, jsonb
) from public, anon, authenticated;
grant execute on function public.persist_completed_diagnosis(
  uuid, text, season_type, season_type, numeric, boolean, season_type, text,
  numeric, text, jsonb, text, jsonb
) to service_role;

-- ---------------------------------------------------------------------------
-- claim_diagnosis — attach a guest diagnosis to the calling user. Idempotent:
-- re-claiming a row you already own succeeds silently (retries after a lost
-- response are safe). Claiming someone else's row fails.
-- ---------------------------------------------------------------------------
create or replace function public.claim_diagnosis(p_diagnosis_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id text := (select auth.jwt()->>'sub');
begin
  if v_user_id is null then
    raise exception 'not authenticated';
  end if;

  -- Reactivate tombstoned accounts on re-signup.
  insert into public.users (id) values (v_user_id)
  on conflict (id) do update set deleted_at = null;

  update public.diagnoses
  set user_id = v_user_id
  where id = p_diagnosis_id
    and user_id is null
    and deleted_at is null;

  if not found then
    -- Idempotent success if this user already owns it.
    if exists (
      select 1 from public.diagnoses
      where id = p_diagnosis_id and user_id = v_user_id and deleted_at is null
    ) then
      return;
    end if;
    raise exception 'diagnosis not found, already claimed, or deleted';
  end if;
end;
$$;

revoke execute on function public.claim_diagnosis(uuid) from public, anon;
grant execute on function public.claim_diagnosis(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- soft_delete_diagnosis — tombstone an owned diagnosis AND its draping rounds.
-- Idempotent: deleting an already-deleted own row succeeds silently.
-- ---------------------------------------------------------------------------
create or replace function public.soft_delete_diagnosis(p_diagnosis_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id text := (select auth.jwt()->>'sub');
begin
  if v_user_id is null then
    raise exception 'not authenticated';
  end if;

  update public.diagnoses
  set deleted_at = now()
  where id = p_diagnosis_id
    and user_id = v_user_id
    and deleted_at is null;

  if not found and not exists (
    select 1 from public.diagnoses
    where id = p_diagnosis_id and user_id = v_user_id
  ) then
    raise exception 'diagnosis not found or not owned by caller';
  end if;

  update public.drape_responses
  set deleted_at = now()
  where diagnosis_id = p_diagnosis_id
    and deleted_at is null;
end;
$$;

revoke execute on function public.soft_delete_diagnosis(uuid) from public, anon;
grant execute on function public.soft_delete_diagnosis(uuid) to authenticated;

commit;
